In [3]:
import torch


In [4]:
torch.cuda.is_available()

False

In [5]:
torch.tensor(9)

tensor(9)

In [6]:
revenue = torch.tensor([34,34,24,53,24])

In [7]:
revenue[3]

tensor(53)

In [8]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
device

    

device(type='cpu')

In [9]:
customer_data = torch.rand(1_00_000,3,device= device)
customer_data.shape

torch.Size([100000, 3])

In [10]:
customer_data[:5]

tensor([[0.5078, 0.2105, 0.5081],
        [0.1783, 0.9924, 0.9544],
        [0.0955, 0.9772, 0.4803],
        [0.5288, 0.1756, 0.6200],
        [0.5006, 0.2376, 0.5779]])

In [11]:
customer_data[:,1]


tensor([0.2105, 0.9924, 0.9772,  ..., 0.5832, 0.4801, 0.7604])

In [12]:
high_spending_customer= customer_data[customer_data[:,1]>0.5]
high_spending_customer

tensor([[0.1783, 0.9924, 0.9544],
        [0.0955, 0.9772, 0.4803],
        [0.9064, 0.5247, 0.4786],
        ...,
        [0.3225, 0.7039, 0.6845],
        [0.5319, 0.5832, 0.5175],
        [0.6040, 0.7604, 0.7463]])

In [13]:
high_spending_customer.shape

torch.Size([49876, 3])

In [14]:
high_spending_customer.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
venue = torch.tensor([
    [34,34,24,53,24],
    [34,54,33,24,32]
])

In [ ]:
venue

In [ ]:
venue.view(-1)

In [ ]:
venue.device

In [ ]:
venue.view(5,2)

In [ ]:
venue[1,4] = 333

In [ ]:
venue

In [ ]:
torch.rand(3,4)

In [ ]:
torch.zeros(3,4)

In [ ]:
material_cost = torch.tensor(10,requires_grad= True, dtype = torch.float16)
print(material_cost)

In [29]:
import torch

x = torch.tensor(2.0, requires_grad=True)

for i in range(2):
    y = x * 3   # y = 3x
    y.backward()
    print(f"Iteration {i+1}, Gradient in x.grad: {x.grad}")


Iteration 1, Gradient in x.grad: 3.0
Iteration 2, Gradient in x.grad: 6.0


In [31]:
import torch

x = torch.tensor(2.0, requires_grad=True)

for i in range(2):
    y = x * 3   # y = 3x
    y.backward()
    print(f"Iteration {i+1}, Gradient in x.grad: {x.grad}")
    x.grad.zero_()   # Reset gradient after use


Iteration 1, Gradient in x.grad: 3.0
Iteration 2, Gradient in x.grad: 3.0
